export const colors = {
  light: {
    background: '#ffffff',
    surface: '#f5f5f5',
    primary: '#6c5ce7',
    primaryDark: '#5a4bd1',
    secondary: '#00cec9',
    text: '#2d3436',
    textSecondary: '#636e72',
    border: '#dfe6e9',
    error: '#d63031',
    success: '#00b894',
    warning: '#fdcb6e',
    card: '#ffffff',
    chatBubbleUser: '#6c5ce7',
    chatBubbleAssistant: '#f0f0f0',
    chatTextUser: '#ffffff',
    chatTextAssistant: '#2d3436',
  },
  dark: {
    background: '#1a1a2e',
    surface: '#16213e',
    primary: '#6c5ce7',
    primaryDark: '#5a4bd1',
    secondary: '#00cec9',
    text: '#eee',
    textSecondary: '#b2bec3',
    border: '#2d3436',
    error: '#ff7675',
    success: '#55efc4',
    warning: '#ffeaa7',
    card: '#16213e',
    chatBubbleUser: '#6c5ce7',
    chatBubbleAssistant: '#2d3436',
    chatTextUser: '#ffffff',
    chatTextAssistant: '#eee',
  },
} as const;

export type ThemeColors = { [K in keyof typeof colors.light]: string };
